//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PardisDBEntities : DbContext
    {
        public PardisDBEntities()
            : base("name=PardisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Sliders> Sliders { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<BaseInfo> BaseInfo { get; set; }
        public virtual DbSet<UserTasks> UserTasks { get; set; }
        public virtual DbSet<vwTask> vwTask { get; set; }
        public virtual DbSet<LogUserLogin> LogUserLogin { get; set; }
    }
}
