//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sliders
    {
        public int SlideID { get; set; }
        public string SlideName { get; set; }
        public string SlideLink { get; set; }
        public string ImageName { get; set; }
        public string ClassName { get; set; }
        public bool IsActive { get; set; }
    }
}
