//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyEquipments
    {
        public long ID { get; set; }
        public long RequestID { get; set; }
        public int ProfileID { get; set; }
        public int NeedID { get; set; }
        public string RequestTitle { get; set; }
        public System.DateTime PriceAnnouncementDeadline { get; set; }
        public System.DateTime DeliveryDeadline { get; set; }
        public Nullable<short> RequestTypeID { get; set; }
        public string WarrantyTerms { get; set; }
        public string Description { get; set; }
    
        public virtual tbl_needs tbl_needs { get; set; }
        public virtual tbl_profiles tbl_profiles { get; set; }
    }
}
