//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_needs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_needs()
        {
            this.SupplyEquipments = new HashSet<SupplyEquipments>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<bool> factorneed { get; set; }
        public Nullable<System.DateTime> factordate { get; set; }
        public string factorip { get; set; }
        public string factorby { get; set; }
        public Nullable<int> profileid { get; set; }
        public Nullable<int> catid { get; set; }
        public string subcatid { get; set; }
        public Nullable<int> sectorid { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public string confirmby { get; set; }
        public string confirmip { get; set; }
        public Nullable<System.DateTime> confirmdate { get; set; }
        public Nullable<int> progress { get; set; }
        public Nullable<bool> iscampaign { get; set; }
        public Nullable<int> nexttime { get; set; }
        public Nullable<int> nextdates { get; set; }
        public string laststatusdesc { get; set; }
        public Nullable<System.DateTime> laststatusdescdates { get; set; }
        public string laststatusdescby { get; set; }
        public Nullable<System.DateTime> toclnd { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> csproviderid { get; set; }
        public string editedby { get; set; }
        public string editedip { get; set; }
        public Nullable<System.DateTime> editeddate { get; set; }
        public Nullable<int> userid { get; set; }
        public string assignby { get; set; }
        public Nullable<System.DateTime> assigndate { get; set; }
        public Nullable<int> departmentid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyEquipments> SupplyEquipments { get; set; }
    }
}
