//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_profiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_profiles()
        {
            this.SupplyEquipments = new HashSet<SupplyEquipments>();
        }
    
        public int id { get; set; }
        public Nullable<int> isperson { get; set; }
        public Nullable<int> birthdate { get; set; }
        public string birthplace { get; set; }
        public Nullable<System.DateTime> registerdate { get; set; }
        public string fathername { get; set; }
        public string name { get; set; }
        public string uniquename { get; set; }
        public string repname { get; set; }
        public string password { get; set; }
        public string code { get; set; }
        public string manager { get; set; }
        public string idnumber { get; set; }
        public string place { get; set; }
        public Nullable<int> edulevel { get; set; }
        public string edufield { get; set; }
        public string job { get; set; }
        public string country { get; set; }
        public string postalcode { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public string comment { get; set; }
        public Nullable<int> howyouknowid { get; set; }
        public Nullable<int> usergroup { get; set; }
        public Nullable<int> isProvider { get; set; }
        public Nullable<bool> acccotactconfirm { get; set; }
        public Nullable<bool> iscampaign { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyEquipments> SupplyEquipments { get; set; }
    }
}
