//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMenuGroup
    {
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsCartable { get; set; }
        public int NodeID { get; set; }
        public string Path { get; set; }
        public int GroupID { get; set; }
        public string GroupTitle { get; set; }
    }
}
