//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRequestNodeStatus
    {
        public long ActivityID { get; set; }
        public long PreActivityID { get; set; }
        public short WorkFlowID { get; set; }
        public int FromNodeID { get; set; }
        public int ToNodeID { get; set; }
        public short StatusId { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string ActivityUserAccount { get; set; }
        public string ToUserAccount { get; set; }
        public int GroupID { get; set; }
        public bool LogicalDelete { get; set; }
        public string ActivityDescription { get; set; }
        public string FromNodeTitle { get; set; }
        public string ToNodeTitle { get; set; }
        public long RequestID { get; set; }
        public System.DateTime RegDate { get; set; }
        public string UserAccount { get; set; }
        public short RequestTypeID { get; set; }
    }
}
