//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTask
    {
        public long UTID { get; set; }
        public long UserID { get; set; }
        public string UserName { get; set; }
        public long TaskID { get; set; }
        public string TaskName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public short Status { get; set; }
        public string StatusTitle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
