//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFAssignments
    {
        public int ID { get; set; }
        public short WorkFlowID { get; set; }
        public int FromNodeID { get; set; }
        public int ToNodeID { get; set; }
        public bool DoConfirm { get; set; }
        public bool DoReject { get; set; }
        public bool DoReturn { get; set; }
    }
}
